name: on_issue_assignment

on:
  issues:
    types: [assigned]

jobs:
  create_issue_branch:
    runs-on: ubuntu-latest
    steps:
      - name: create issue branch
        uses: robvanderleek/create-issue-branch@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  move_project_card:
    runs-on: ubuntu-latest
    steps:
      - name: move project card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Board
          column-name: In progress
          issue-number: ${{ github.event.issue.number }}
