name: on_issue_creation

on:
  issues:
    types: [opened]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_project_card:
    runs-on: ubuntu-latest
    steps:
      - name: create project card
        uses: peter-evans/create-or-update-project-card@v1
        with:
          project-name: Board
          column-name: To do
          issue-number: ${{ github.event.issue.number }}
