name: test_gpu

on:
  pull_request:
    types: [ready_for_review]

jobs:
  run:
    runs-on: [self-hosted,cml,gpu]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cache-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-cache-
      - name: install
        run: |
          # python3 -m pip install -r requirements.txt
          python3 -m pip install --no-deps -e .
      - name: run cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEPTUNE_API_TOKEN:  ${{ secrets.NEPTUNE_API_TOKEN }}
        run: |
          # dvc pull --run-cache
          # dvc repro

          echo "## Metrics" > report.md
          git fetch --prune
          dvc metrics diff main --show-md >> report.md

          cml-send-comment report.md
      - uses: EndBug/add-and-commit@v7.0.0
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "CML: add changes"
